/*
  geo-core.js 
  Copyright 2005-2010 :-), Inc., released under the Clear BSD  license.

  Includes compressed code under the following licenses:

  (For uncompressed versions of the code used please see the
  Geo-Core GIT repository: ...)
*/
﻿
Ext.ns("Geo");Geo.WSGIScriptAlias='';Geo.UriTemplate={groupStaticBbox:'group/staticbbox',groupWithinPoint:'group/withinpoint',groupWithinBbox:'group/withinbbox',groupClosestPoint:'group/closestpoint',layer:'layer/',layerQuery:'layer/query',layerBbox:'layer/bbox',layerStaticBbox:'layer/staticbbox',layerMetadata:'layer/metadata',metadataDistinctValues:'metadata/distinct_values',getUri:function(action,option){var hostname='http://'+window.location.hostname+':'+window.location.port+'/';return hostname+Geo.WSGIScriptAlias+'/'+Geo.UriTemplate[action]+(option||'');}};Ext.ns("Geo.core");Geo.core.Group=Ext.extend(Ext.util.Observable,{constructor:function(config){this.addEvents('staticbbox','withinpoint','withinbbox','closestpoint');Geo.core.Group.superclass.constructor.call(config);},getStaticBBox:function(layers){var params={layers:layers};Ext.Ajax.request({url:Geo.UriTemplate.getUri('groupStaticBbox'),method:'Post',headers:{'Content-Type':'text/json'},jsonData:params,scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('staticbbox',result);}});},getWithInPoint:function(layers,fields,point,dist){var params={layers:layers,fields:fields,point:point,dist:dist};Ext.Ajax.request({url:Geo.UriTemplate.getUri('groupWithinPoint'),method:'Post',headers:{'Content-Type':'text/json'},jsonData:params,scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('withinpoint',result);}});},getWithInBBox:function(layers,bbox){var params={layers:layers,bbox:bbox};Ext.Ajax.request({url:Geo.UriTemplate.getUri('groupWithinBbox'),method:'Post',headers:{'Content-Type':'text/json'},jsonData:params,scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('withinbbox',result);}});},getClosestPoint:function(layers,point){var params={layers:layers,point:point};Ext.Ajax.request({url:Geo.UriTemplate.getUri('groupClosestPoint'),method:'Post',headers:{'Content-Type':'text/json'},jsonData:params,scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('closestpoint',result.points);}});}});Ext.ns("Geo.core");Geo.core.Layer=Ext.extend(Ext.util.Observable,{constructor:function(config){this.addEvents('query','metadata','bbox','staticbbox');Geo.core.Layer.superclass.constructor.call(config);},query:function(layer,fields,criteria,paging,start,limit,wkt){paging=paging||false;start=start||0;limit=limit||0;wkt=wkt||false;if(!criteria)
criteria=[];var p={paging:paging,start:start,limit:limit,layer:layer,fields:fields,criteria:criteria,wkt:wkt};Ext.Ajax.request({url:Geo.UriTemplate.getUri('layerQuery'),method:'Post',headers:{'Content-Type':'text/json'},jsonData:p,scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('query',result);}});},getMetadata:function(layerName){var p={layerName:layerName};Ext.Ajax.request({url:Geo.UriTemplate.getUri('layerMetadata','?'+Ext.urlEncode(p)),method:'Get',headers:{'Content-Type':'text/json'},scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('metadata',result);}});},getBBox:function(layerName,srid){var srid=srid||'96';var p={layerName:layerName,srid:srid};Ext.Ajax.request({url:Geo.UriTemplate.getUri('layerBbox','?'+Ext.urlEncode(p)),method:'Get',headers:{'Content-Type':'text/json'},scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('bbox',result);}});},getStaticBBox:function(layerName){var p={layerName:layerName};Ext.Ajax.request({url:Geo.UriTemplate.getUri('layerStaticBbox','?'+Ext.urlEncode(p)),method:'Get',headers:{'Content-Type':'text/json'},scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('staticbbox',result);}});}});Ext.ns("Geo.core");Geo.core.Metadata=Ext.extend(Ext.util.Observable,{constructor:function(config){this.addEvents('distinct_values');Geo.core.Metadata.superclass.constructor.call(config);},getDistinctValues:function(name,layer,limit){var p={name:name,layer:layer,limit:limit};Ext.Ajax.request({url:Geo.UriTemplate.getUri('metadataDistinctValues','?'+Ext.urlEncode(p)),method:'Get',headers:{'Content-Type':'text/json'},scope:this,success:function(response,options){var result=Ext.util.JSON.decode(response.responseText);this.fireEvent('distinct_values',result);}});}});